"""
Django settings for webapps project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ddrij4#s%rj+*%ncdtaqfu9d+3*(2d2p_h2kc5p5!i_51dim52'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# set up allowed hosts if debug mode is turned off
ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'site_models',
    'login',
    'registration',
    'grumble_stream',
    'user_profile'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grumblr_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # include the global templates directory
            os.path.join(BASE_DIR, "grumblr_site/templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # a context processor that allows serving media files (user uploaded files) to template
                # through URL, i.e. {{ MEDIA_URL }}
                # TODO: this context processor doesn't work at all in Django 1.11; add this line to the end of
                # urls.py instead: urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
                # with django.conf.settings and django.conf.urls.static.static()
                # 'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
# also the global static files directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'grumblr_site/static')
]

# URL that handles the media served from MEDIA_ROOT, used for managing stored files
MEDIA_URL = '/media/'
# absolute filesystem path to the directory that will hold user-uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'grumblr_site/media')

# URL to use if the authentication system requires a user to log in
LOGIN_URL = '/login'
# default URL to redirect to after a user logs in
LOGIN_REDIRECT_URL = '/'

# configure Django to just print emails rather than sending them
# comment out this line to enable real email-sending
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# to enable real email-sending, uncomment and configure the settings below
# for more: https://docs.djangoproject.com/en/1.11/topics/email/#smtp-backend
# EMAIL_HOST = 'Your-SMTP-host'
# EMAIL_HOST_USER = 'Your-SMTP-username'
# EMAIL_HOST_PASSWORD = 'Your-SMTP-password'
# EMAIL_USE_TLS = True
